language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.5
      env: TOXENV=py35
    - python: 2.7
      env: TOXENV=py27


# before_install:
#   - sudo apt-get install packageA
#   - pip install packageB

# install dependencies
install: pip install tox

# command to run tests, e.g. python setup.py test
script: tox

## safelist
#branches:
#  only:
#  - master
#  - develop

#deploy:
#  provider: pypi
#  user: simomarsili
#  password: $PYPI_PASS
##  server: https://test.pypi.org/legacy/
#  distributions: "sdist bdist_wheel"
#  on:
#    branch: master
#    condition: $TRAVIS_PYTHON_VERSION = "3.6"